// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package org.apache.dubbo.remoting.transport.grpc.proto;

public interface GrpcRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.GrpcRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string data = 1;</code>
   */
  String getData();
  /**
   * <code>string data = 1;</code>
   */
  com.google.protobuf.ByteString
      getDataBytes();
}
